version: "2"

services:
  paperwork:
     image: conoria/paperwork
     links:
          - paperwork-db:paperwork-db
  #uncomment the following to use with MySQL. By default it will use flat files
  #paperwork-db:
  #   image: mariadb
  #   environment:
  #        - MYSQL_ROOT_PASSWORD=paperwork
  #        - MYSQL_DATABASE=paperwork
  #        - MYSQL_USER=paperwork
  #        - MYSQL_PASSWORD=paperwork

