version: "2"

volumes:
  nc:
  db:

services:
  db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress123
     volumes:
          - .db:/var/lib/mysql

  nc:
     depends_on:
          - db
     image: nextcloud:latest
     links:
          - db
     restart: always
     ports:
          - 8080:80
     volumes:
          - .data:/var/www/html

  collabora:
     image: collabora/code
     restart: always
     environment:
         extra_params: --o:ssl.enable=false
