version: "2"

services:
  paperwork:
     image: tpaulus/paperwork-docker
     links:
          - paperwork-db:paperwork-db
     ports:
             - "9090:80"
  paperwork-db:
     image: mariadb
     environment:
          - MYSQL_ROOT_PASSWORD=paperwork
          - MYSQL_DATABASE=paperwork
          - MYSQL_USER=paperwork
          - MYSQL_PASSWORD=paperwork

